---
title: "figures for Asamoto et al. 2024"
date: "Last knitted on `r format(Sys.Date(), '%d %b %Y')`"
author: "Ciara Asamoto, Sebastian Kopf"
output:
  html_document: 
    css: stylesheet.css
    toc: yes
    toc_float: yes
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyr)
library(dplyr)
library(knitr)
library(readxl)
library(writexl)
library(phytools)
library(ggmsa)
library(ggpubr)

```

# read in data
```{r}
fig_df <- read_xlsx("data/figure_df.xlsx")
lit_df <- read_xlsx("data/lit_data.xlsx")

full_df <- full_join(fig_df, lit_df) 

```

# NarG Tree
```{r}
nar_tree <- read.nexus("data/narG_seqs.nex.con.tre")

# rename tips
new_tip_labels <- c("C. marinum", "A. aromaticum", "T. aromatica", "P. denitrificans", "P. aeruginosa Y62H C221A", "P. aeruginosa C221", "P. aeruginosa", "P. aeruginosa Y62", "P. chlororaphis", "P. stutzeri", "S. carnosus", "B. bataviensis", "B. vireti")

# copy the new tip labels into your tree data
nar_tree$tip.label <- new_tip_labels

# plot tree
plot(nar_tree, use.edge.length = FALSE)

#nodelabels() # use if you want to see node labels
new_tree <- rotateNodes(nar_tree, 14) 
new_tree <- rotateNodes(new_tree, 19)

plot(new_tree, use.edge.length = FALSE)

```

# Stable Isotope Summary
```{r}
# reorder the strains to match the order of the NarG tree
sum_reorder <- full_df %>% 
  mutate(
    exp = factor(exp, levels = c("BV", "BB", "SC", "CM", "Pstutzeri", "PC","Y62","C221","double", "Dnap", "PD", "TA", "AA"))
  )

# 18e/15e plot
on_plot <- sum_reorder %>% 
  ggplot() +
  aes(x = mean_ON_ratio, y = exp) +
  geom_errorbar(aes(xmin = min_ON_ratio, xmax = max_ON_ratio), width=0) +
  scale_y_discrete(limits = rev) +
  theme_bw() +
  geom_point(size = 3, color = c("black","black","black","black","black","black","#3399FF","#3399FF","black","black","black","black", "black")) +
  theme(panel.grid.minor = element_blank(), panel.grid.major.y = element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), text = element_text(size =14)) +
  xlab(bquote(phantom()^"18"~epsilon / phantom()^"15" ~ epsilon)) +
  ylab("")

# 15e summary
eps15_plot <- sum_reorder %>% 
  ggplot() +
  aes(x = mean_eps15, y = exp) +
  geom_errorbar(aes(xmin = min_eps15, xmax = max_eps15), width=0) +
  scale_y_discrete(limits = rev) +
  theme_bw() +
  geom_point(size = 3) +
  theme(panel.grid.minor = element_blank(), panel.grid.major.y = element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), text = element_text(size = 14)) +
  xlab(bquote(phantom()^"15" ~ epsilon)) +
  ylab("")

# 18e summary
eps18_plot <- sum_reorder %>% 
  ggplot() +
  aes(x = mean_eps18, y = exp) +
  geom_errorbar(aes(xmin = min_eps18, xmax = max_eps18), width=0) +
  scale_y_discrete(limits = rev) +
  theme_bw() +
  geom_point(size = 3) +
  theme(panel.grid.minor = element_blank(), panel.grid.major.y = element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), text = element_text(size = 14)) +
  xlab(bquote(phantom()^"18" ~ epsilon)) +
  ylab("")


iso_fig <- ggarrange(on_plot, eps15_plot, eps18_plot, ncol = 3)

iso_fig

```

# NarG consensus logo
## locate alignment
```{r}
NarG_sequences <-"data/narG_align.fasta"

```

## define color palette
```{r}
library(pals)

color <- c("#CC3366","#CC3366","#CC3366","#CC3366","#CC3366","#CC99CC","#CC99CC","#CC99CC","#339966","#339966","#339966", "#336699","#336699", "#99CC33","#99CC33","#99CC33","#99CC33", "#FF9933","#FF9933","#FFCC33", "#FFFFFF")
names <- c("I","L","V", "A","M", "F", "W","Y", "K", "R","H","D","E","S", "T", "N", "Q", "P", "G", "C", "-")

custom_palette <- data.frame(names, color)
pals::pal.bands(custom_palette$color)
```

## plot C221A 
```{r}
ggmsa(NarG_sequences, 222, 244, font = "DroidSansMono", char_width = 0.5, seq_name = TRUE, custom_color = custom_palette) + geom_seqlogo(custom_color = custom_palette)

```

## plot Y62H
```{r}
ggmsa(NarG_sequences, 52, 74, font = "DroidSansMono", char_width = 0.5, seq_name = TRUE, custom_color = custom_palette) + geom_seqlogo(custom_color = custom_palette)
```
